language: cpp

compiler:
  - gcc
  - clang
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      before_install:
        - sudo apt-get install openjdk-8-jdk
        - sudo apt-get install maven
    #- os: osx
    #  python: 2.7
    #  before_install:
    #    - brew install maven

before_install:
  #- sudo pip install cpp-coveralls wheel
  # use miniconda for python package testing
  #- wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  #- bash miniconda.sh -b -p $HOME/miniconda
  #- export PATH="$HOME/miniconda/bin:$PATH"
  #- hash -r
  #- conda config --set always_yes yes --set changeps1 no
  #- conda update -q conda
  #- conda create -q -n test-python27 python=2.7 nomkl numpy scipy scikit-learn
script:
  #- make all
  - make java
  #- make python
  #- mvn clean test -f java/pom.xml
  #- make test
  #- make test_gcov --always-make
  #- cd python
  #- source activate test-python27
  #- pip install pytest readme_renderer
  #- python setup.py check -mrs
  #- python setup.py install
  #- py.test tests
  #- source deactivate
  #- cd ..
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
